// Penjualan › Tambah Pesanan: customer, location, Vani1 (Scan produk) + Vani2 (Tambah Baru), Sudah Lunas, courier -> Simpan -> Siap Proses -> Proses Pesanan.
const { test, expect } = require('../../fixtures/test-fixtures');
const { SalesOrderPage } = require('../../pages/SalesOrderPage');
const { env } = require('../../utils/env');
const allure = require('allure-js-commons');
const { attachScreenshot, pauseForDemo } = require('../../utils/report-helper');

test('Sales - create an order and process it', async ({ page, pendingProductRequests }) => {
  await allure.epic('Jubelio');
  await allure.feature('Penjualan');
  await allure.story('Buat pesanan dan proses');
  await allure.severity('critical');

  const sales = new SalesOrderPage(page, pendingProductRequests);
  let order;

  await test.step('Tambah Pesanan: customer, location, products, paid, courier', async () => {
    await sales.openList();
    await sales.startNewOrder();
    await sales.fillHeader(env.customer, env.location);
    await sales.addProducts(env.products);
    await sales.setSudahLunas();
    await sales.setCourier(env.courier);
    await attachScreenshot(page, 'Form Tambah Pesanan terisi');
  });

  await test.step('Simpan (No. Pesanan is generated by Jubelio)', async () => {
    order = await sales.save();
    expect(order.no).toMatch(/^SO-\d+$/);
    console.log(`>> Order no: ${order.no}`);
    await allure.parameter('No. Pesanan', order.no);
    await attachScreenshot(page, `Pesanan ${order.no} tersimpan`);
  });
  
await test.step('Siap Proses -> cari pesanan', async () => {
    await sales.findInSiapProses(order.no);
    await attachScreenshot(page, `Pesanan ${order.no} di Siap Proses`);
    await pauseForDemo(page);
  });
});
