// Penjualan › Tambah Pesanan: customer, location, Vani1 (Scan produk) + Vani2 (Tambah Baru), Sudah Lunas, courier -> Simpan -> Siap Proses -> Proses Pesanan.
const { test, expect } = require('../../fixtures/test-fixtures');
const { SalesOrderPage } = require('../../pages/SalesOrderPage');
const { env } = require('../../utils/env');

test('Sales - create an order and process it', async ({ page, pendingProductRequests }) => {
  const sales = new SalesOrderPage(page, pendingProductRequests);
  let order;

  await test.step('Tambah Pesanan: customer, location, products, paid, courier', async () => {
    await sales.openList();
    await sales.startNewOrder();
    await sales.fillHeader(env.customer, env.location);
    await sales.addProducts(env.products);
    await sales.setSudahLunas();
    await sales.setCourier(env.courier);
  });

  await test.step('Simpan (No. Pesanan is generated by Jubelio)', async () => {
    order = await sales.save();
    expect(order.no).toMatch(/^SO-\d+$/);
    console.log(`>> Order no: ${order.no}`);
  });

  await test.step('Siap Proses -> Proses Pesanan', async () => {
    await sales.processOrder(order.no);
  });
});
